/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestCasesCustomNewRouteImport } from './routes/test-cases/custom.new'
import { Route as TestCasesCustomIdRouteImport } from './routes/test-cases/custom.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesCustomNewRoute = TestCasesCustomNewRouteImport.update({
  id: '/test-cases/custom/new',
  path: '/test-cases/custom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesCustomIdRoute = TestCasesCustomIdRouteImport.update({
  id: '/test-cases/custom/$id',
  path: '/test-cases/custom/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/projects'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/projects'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/projects'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  HomepageRoute: typeof HomepageRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRoute
  TestCasesCustomIdRoute: typeof TestCasesCustomIdRoute
  TestCasesCustomNewRoute: typeof TestCasesCustomNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases/custom/new': {
      id: '/test-cases/custom/new'
      path: '/test-cases/custom/new'
      fullPath: '/test-cases/custom/new'
      preLoaderRoute: typeof TestCasesCustomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases/custom/$id': {
      id: '/test-cases/custom/$id'
      path: '/test-cases/custom/$id'
      fullPath: '/test-cases/custom/$id'
      preLoaderRoute: typeof TestCasesCustomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  HomepageRoute: HomepageRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRoute,
  TestCasesCustomIdRoute: TestCasesCustomIdRoute,
  TestCasesCustomNewRoute: TestCasesCustomNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
