/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as TestSuitesRouteImport } from './routes/test-suites'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as StoriesIdRouteImport } from './routes/stories/$id'
import { Route as ProjectsIdRouteImport } from './routes/projects/$id'
import { Route as TestCasesCustomNewRouteImport } from './routes/test-cases/custom.new'
import { Route as TestCasesCustomIdRouteImport } from './routes/test-cases/custom.$id'

const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSuitesRoute = TestSuitesRouteImport.update({
  id: '/test-suites',
  path: '/test-suites',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesCustomNewRoute = TestCasesCustomNewRouteImport.update({
  id: '/test-cases/custom/new',
  path: '/test-cases/custom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesCustomIdRoute = TestCasesCustomIdRouteImport.update({
  id: '/test-cases/custom/$id',
  path: '/test-cases/custom/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/test-suites': typeof TestSuitesRoute
  '/wiki': typeof WikiRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/test-suites': typeof TestSuitesRoute
  '/wiki': typeof WikiRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/test-suites': typeof TestSuitesRoute
  '/wiki': typeof WikiRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/test-cases/custom/$id': typeof TestCasesCustomIdRoute
  '/test-cases/custom/new': typeof TestCasesCustomNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/settings'
    | '/test-suites'
    | '/wiki'
    | '/projects/$id'
    | '/stories/$id'
    | '/projects/'
    | '/stories/'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/settings'
    | '/test-suites'
    | '/wiki'
    | '/projects/$id'
    | '/stories/$id'
    | '/projects'
    | '/stories'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/404'
    | '/homepage'
    | '/login'
    | '/settings'
    | '/test-suites'
    | '/wiki'
    | '/projects/$id'
    | '/stories/$id'
    | '/projects/'
    | '/stories/'
    | '/test-cases/custom/$id'
    | '/test-cases/custom/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  HomepageRoute: typeof HomepageRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TestSuitesRoute: typeof TestSuitesRoute
  WikiRoute: typeof WikiRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  StoriesIdRoute: typeof StoriesIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  TestCasesCustomIdRoute: typeof TestCasesCustomIdRoute
  TestCasesCustomNewRoute: typeof TestCasesCustomNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-suites': {
      id: '/test-suites'
      path: '/test-suites'
      fullPath: '/test-suites'
      preLoaderRoute: typeof TestSuitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases/custom/new': {
      id: '/test-cases/custom/new'
      path: '/test-cases/custom/new'
      fullPath: '/test-cases/custom/new'
      preLoaderRoute: typeof TestCasesCustomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases/custom/$id': {
      id: '/test-cases/custom/$id'
      path: '/test-cases/custom/$id'
      fullPath: '/test-cases/custom/$id'
      preLoaderRoute: typeof TestCasesCustomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  HomepageRoute: HomepageRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TestSuitesRoute: TestSuitesRoute,
  WikiRoute: WikiRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  StoriesIdRoute: StoriesIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  TestCasesCustomIdRoute: TestCasesCustomIdRoute,
  TestCasesCustomNewRoute: TestCasesCustomNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
